apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-exporter.name" . }}
    helm.sh/chart: {{ include "kafka-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kafka-exporter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
          "ad.datadoghq.com/{{ .Chart.Name }}.check_names": |
            ["openmetrics"]
          "ad.datadoghq.com/{{ .Chart.Name }}.init_configs": |
            [{}]
          "ad.datadoghq.com/{{ .Chart.Name }}.instances": |
            [
              {
                "prometheus_url": "http://%%host%%:%%port_metrics%%/metrics",
                "namespace": "kafka_exporter",
                "metrics": [ {
                  "kafka_brokers": "kafka_brokers",
                  "kafka_topic_partitions": "kafka_topic_partitions",
                  "kafka_topic_partition_current_offset": "kafka_topic_partition_current_offset",
                  "kafka_topic_partition_oldest_offset": "kafka_topic_partition_oldest_offset",
                  "kafka_topic_partition_in_sync_replica": "kafka_topic_partition_in_sync_replica",
                  "kafka_topic_partition_leader": "kafka_topic_partition_leader",
                  "kafka_topic_partition_leader_is_preferred": "kafka_topic_partition_leader_is_preferred",
                  "kafka_topic_partition_replicas": "kafka_topic_partition_replicas",
                  "kafka_topic_partition_under_replicated_partition": "kafka_topic_partition_under_replicated_partition",
                  "kafka_consumergroup_current_offset": "kafka_consumergroup_current_offset",
                  "kafka_consumergroup_lag": "kafka_consumergroup_lag"
                }]
              }
            ]
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.kafkaExporter}}
            {{- range .Values.kafkaExporter.kafka.servers }}
            - "--kafka.server={{ . }}"
            {{- end }}
            {{- if .Values.kafkaExporter.kafka.version }}
            - --kafka.version={{ .Values.kafkaExporter.kafka.version }}
            {{- end }}
            {{- end}}
            {{- if .Values.kafkaExporter.sasl.enabled }}
            - --sasl.enabled
            {{- if not .Values.kafkaExporter.sasl.handshake }}
            - --sasl.handshake=false
            {{- end }}
            - --sasl.username={{ .Values.kafkaExporter.sasl.username }}
            - --sasl.password={{ .Values.kafkaExporter.sasl.password }}
            {{- end }}
            {{- if .Values.kafkaExporter.tls.enabled}}
            - --tls.enabled
            - --tls.ca-file=/etc/tls-certs/ca-file
            - --tls.cert-file=/etc/tls-certs/cert-file
            - --tls.key-file=/etc/tls-certs/key-file
            {{- end }}
            {{- if .Values.kafkaExporter.log }}
            - --log.level={{ .Values.kafkaExporter.log.level }}
            {{- if .Values.kafkaExporter.log.enableSarama }}
            - --log.enable-sarama
            {{- end }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: 9308
              protocol: TCP
          {{- if .Values.kafkaExporter.tls.enabled }}
          volumeMounts:
          - name: tls-certs
            mountPath: "/etc/tls-certs/"
            readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}

      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.kafkaExporter.tls.enabled }}
      volumes:
      - name: tls-certs
        secret:
          secretName: {{ include "kafka-exporter.fullname" . }}
    {{- end }}
